# Generated by Django 6.1.1 on 2026-09-04 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assignment_type', models.CharField(choices=[('fixed', 'Fixed'), ('rotating', 'Rotating'), ('claimable', 'Claimable')], max_length=10)),
                ('recurrence_interval_days', models.PositiveIntegerField(help_text="Days between occurrences, e.g. 3 for 'every 3 days', 14 for 'every other <weekday>'.")),
                ('recurrence_weekday', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text="Optional anchor weekday, e.g. Monday for 'every other Monday'.", null=True)),
                ('last_done', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.member')),
            ],
            options={
                'ordering': ['-done_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoreRotationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_slots', to='core.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='chore',
            name='current_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_chores', to='core.member'),
        ),
        migrations.AddField(
            model_name='chore',
            name='fixed_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_chores', to='core.member'),
        ),
        migrations.AddField(
            model_name='chore',
            name='rotation_current',
            field=models.ForeignKey(blank=True, help_text='Member whose turn it is next, for rotating chores.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores_up_next', to='core.member'),
        ),
        migrations.AddField(
            model_name='chore',
            name='rotation_members',
            field=models.ManyToManyField(blank=True, related_name='rotating_chores', through='core.ChoreRotationSlot', to='core.member'),
        ),
        migrations.AddConstraint(
            model_name='chorerotationslot',
            constraint=models.UniqueConstraint(fields=('chore', 'order'), name='unique_chore_rotation_order'),
        ),
        migrations.AddConstraint(
            model_name='chorerotationslot',
            constraint=models.UniqueConstraint(fields=('chore', 'member'), name='unique_chore_rotation_member'),
        ),
    ]
